// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StreamVaultTechnicalAssessment.Data;

#nullable disable

namespace StreamVaultTechnicalAssessment.Migrations
{
    [DbContext(typeof(ContentDbContext))]
    [Migration("20260706013452_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("StreamVaultTechnicalAssessment.DTOs.Content.Content", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AgeRating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ContentType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Contents");

                    b.HasDiscriminator<int>("ContentType");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("StreamVaultTechnicalAssessment.DTOs.Content.Audiobook", b =>
                {
                    b.HasBaseType("StreamVaultTechnicalAssessment.DTOs.Content.Content");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Duration_mins")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Duration_mins");

                    b.Property<string>("Narrator")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue(2);

                    b.HasData(
                        new
                        {
                            Id = "8435f185-895d-4028-b9a5-fc8ad8fde801",
                            AgeRating = "PG",
                            Description = "A marine biologist's memoir of survival and discovery in the world's deepest trenches.",
                            Genre = "Memoir",
                            ReleaseDate = new DateTime(2020, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Whispers of the Deep",
                            Author = "Dr. Susan Cole",
                            Duration_mins = 512,
                            Narrator = "James Holloway"
                        },
                        new
                        {
                            Id = "3f86827a-0b05-4bfb-850f-5a4ef96475d6",
                            AgeRating = "PG-13",
                            Description = "A gripping mystery spanning three generations and one haunted house.",
                            Genre = "Mystery",
                            ReleaseDate = new DateTime(2018, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Clockmaker's Daughter",
                            Author = "Kate Morton",
                            Duration_mins = 764,
                            Narrator = "Fiona Shaw"
                        });
                });

            modelBuilder.Entity("StreamVaultTechnicalAssessment.DTOs.Content.Movie", b =>
                {
                    b.HasBaseType("StreamVaultTechnicalAssessment.DTOs.Content.Content");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Duration_mins")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Duration_mins");

                    b.HasDiscriminator().HasValue(0);

                    b.HasData(
                        new
                        {
                            Id = "d6c4c7bc-2049-4bc6-8b21-6fe063499c93",
                            AgeRating = "PG-13",
                            Description = "A stranded astronaut must decode a mysterious transmission before her oxygen runs out.",
                            Genre = "Sci-Fi",
                            ReleaseDate = new DateTime(2022, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Last Signal",
                            Director = "Elena Marsh",
                            Duration_mins = 118
                        },
                        new
                        {
                            Id = "0e243aa2-532a-4cfc-b650-bfe6379fae0d",
                            AgeRating = "R",
                            Description = "A jazz musician uncovers a family secret during one unforgettable night in Havana.",
                            Genre = "Drama",
                            ReleaseDate = new DateTime(2019, 8, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Midnight in Havana",
                            Director = "Carlos Ibanez",
                            Duration_mins = 104
                        },
                        new
                        {
                            Id = "8a7f86df-9029-4ebd-903a-74e5e4579032",
                            AgeRating = "PG-13",
                            Description = "An elite squad races against time to stop a rogue AI from seizing control of a military satellite.",
                            Genre = "Action",
                            ReleaseDate = new DateTime(2023, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Iron Horizon",
                            Director = "Priya Nair",
                            Duration_mins = 132
                        });
                });

            modelBuilder.Entity("StreamVaultTechnicalAssessment.DTOs.Content.MusicAlbum", b =>
                {
                    b.HasBaseType("StreamVaultTechnicalAssessment.DTOs.Content.Content");

                    b.Property<string>("Artist")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RecordLabel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TrackCount")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue(3);

                    b.HasData(
                        new
                        {
                            Id = "ef3c9098-a1f7-490d-8a36-ec1c8c02a80c",
                            AgeRating = "PG",
                            Description = "A synth-driven concept album exploring isolation in a hyperconnected world.",
                            Genre = "Electronic",
                            ReleaseDate = new DateTime(2023, 4, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Neon Static",
                            Artist = "Vela Nightshade",
                            RecordLabel = "Glasswave Records",
                            TrackCount = 11
                        },
                        new
                        {
                            Id = "03f06ba5-f69d-4d5c-b920-28f7e1d5345a",
                            AgeRating = "G",
                            Description = "An acoustic folk album recorded live across small towns in the American Midwest.",
                            Genre = "Folk",
                            ReleaseDate = new DateTime(2017, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Roads Less Traveled",
                            Artist = "Marlon Cade",
                            RecordLabel = "Independent",
                            TrackCount = 9
                        });
                });

            modelBuilder.Entity("StreamVaultTechnicalAssessment.DTOs.Content.Series", b =>
                {
                    b.HasBaseType("StreamVaultTechnicalAssessment.DTOs.Content.Content");

                    b.Property<int>("TotalEpisodes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalSeasons")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue(1);

                    b.HasData(
                        new
                        {
                            Id = "72683d93-31b5-44b1-8ed8-77e4d1fe92fd",
                            AgeRating = "TV-14",
                            Description = "Three generations of a family navigate secrets buried in a small coastal town.",
                            Genre = "Drama",
                            ReleaseDate = new DateTime(2021, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Beneath the Willow",
                            TotalEpisodes = 24,
                            TotalSeasons = 3
                        },
                        new
                        {
                            Id = "594710ad-0b27-43fe-bcbd-75409e070014",
                            AgeRating = "TV-MA",
                            Description = "A crew of thieves exploits parallel timelines to pull off the ultimate heist.",
                            Genre = "Sci-Fi",
                            ReleaseDate = new DateTime(2024, 1, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Quantum Heist",
                            TotalEpisodes = 8,
                            TotalSeasons = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
