// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StreamVaultTechnicalAssessment.data;

#nullable disable

namespace StreamVaultTechnicalAssessment.Migrations
{
    [DbContext(typeof(ContentDbContext))]
    partial class ContentDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("StreamVaultTechnicalAssessment.dtos.content.Content", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AgeRating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ContentType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Contents");

                    b.HasDiscriminator<int>("ContentType");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("StreamVaultTechnicalAssessment.dtos.content.Audiobook", b =>
                {
                    b.HasBaseType("StreamVaultTechnicalAssessment.dtos.content.Content");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Duration_mins")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Duration_mins");

                    b.Property<string>("Narrator")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue(2);

                    b.HasData(
                        new
                        {
                            Id = "c4b7bdea-8d56-4aca-b757-d0c35c017b70",
                            AgeRating = "PG",
                            Description = "A marine biologist's memoir of survival and discovery in the world's deepest trenches.",
                            Genre = "Memoir",
                            ReleaseDate = new DateTime(2020, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Whispers of the Deep",
                            Author = "Dr. Susan Cole",
                            Duration_mins = 512,
                            Narrator = "James Holloway"
                        },
                        new
                        {
                            Id = "5633468e-6d6a-4573-8d53-5439cbce0e88",
                            AgeRating = "PG-13",
                            Description = "A gripping mystery spanning three generations and one haunted house.",
                            Genre = "Mystery",
                            ReleaseDate = new DateTime(2018, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Clockmaker's Daughter",
                            Author = "Kate Morton",
                            Duration_mins = 764,
                            Narrator = "Fiona Shaw"
                        });
                });

            modelBuilder.Entity("StreamVaultTechnicalAssessment.dtos.content.Movie", b =>
                {
                    b.HasBaseType("StreamVaultTechnicalAssessment.dtos.content.Content");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Duration_mins")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Duration_mins");

                    b.HasDiscriminator().HasValue(0);

                    b.HasData(
                        new
                        {
                            Id = "d8968b1a-5dd2-425e-ab41-631925db4e51",
                            AgeRating = "PG-13",
                            Description = "A stranded astronaut must decode a mysterious transmission before her oxygen runs out.",
                            Genre = "Sci-Fi",
                            ReleaseDate = new DateTime(2022, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Last Signal",
                            Director = "Elena Marsh",
                            Duration_mins = 118
                        },
                        new
                        {
                            Id = "671c4181-6612-44c1-9341-bb8b03916609",
                            AgeRating = "R",
                            Description = "A jazz musician uncovers a family secret during one unforgettable night in Havana.",
                            Genre = "Drama",
                            ReleaseDate = new DateTime(2019, 8, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Midnight in Havana",
                            Director = "Carlos Ibanez",
                            Duration_mins = 104
                        },
                        new
                        {
                            Id = "4d890de3-487a-4b1f-a34e-1358a3f74233",
                            AgeRating = "PG-13",
                            Description = "An elite squad races against time to stop a rogue AI from seizing control of a military satellite.",
                            Genre = "Action",
                            ReleaseDate = new DateTime(2023, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Iron Horizon",
                            Director = "Priya Nair",
                            Duration_mins = 132
                        });
                });

            modelBuilder.Entity("StreamVaultTechnicalAssessment.dtos.content.MusicAlbum", b =>
                {
                    b.HasBaseType("StreamVaultTechnicalAssessment.dtos.content.Content");

                    b.Property<string>("Artist")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RecordLabel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TrackCount")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue(3);

                    b.HasData(
                        new
                        {
                            Id = "6f67ea92-e93d-43fb-bbd4-16f2e94de1b1",
                            AgeRating = "PG",
                            Description = "A synth-driven concept album exploring isolation in a hyperconnected world.",
                            Genre = "Electronic",
                            ReleaseDate = new DateTime(2023, 4, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Neon Static",
                            Artist = "Vela Nightshade",
                            RecordLabel = "Glasswave Records",
                            TrackCount = 11
                        },
                        new
                        {
                            Id = "0b6b67ef-8e6b-4b7d-865b-d24c535cb071",
                            AgeRating = "G",
                            Description = "An acoustic folk album recorded live across small towns in the American Midwest.",
                            Genre = "Folk",
                            ReleaseDate = new DateTime(2017, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Roads Less Traveled",
                            Artist = "Marlon Cade",
                            RecordLabel = "Independent",
                            TrackCount = 9
                        });
                });

            modelBuilder.Entity("StreamVaultTechnicalAssessment.dtos.content.Series", b =>
                {
                    b.HasBaseType("StreamVaultTechnicalAssessment.dtos.content.Content");

                    b.Property<int>("TotalEpisodes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalSeasons")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue(1);

                    b.HasData(
                        new
                        {
                            Id = "3f7a409e-5933-48d2-913c-10ac1051b6d7",
                            AgeRating = "TV-14",
                            Description = "Three generations of a family navigate secrets buried in a small coastal town.",
                            Genre = "Drama",
                            ReleaseDate = new DateTime(2021, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Beneath the Willow",
                            TotalEpisodes = 24,
                            TotalSeasons = 3
                        },
                        new
                        {
                            Id = "fb379c2d-7970-4f0a-ae50-b61a36cff31e",
                            AgeRating = "TV-MA",
                            Description = "A crew of thieves exploits parallel timelines to pull off the ultimate heist.",
                            Genre = "Sci-Fi",
                            ReleaseDate = new DateTime(2024, 1, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Quantum Heist",
                            TotalEpisodes = 8,
                            TotalSeasons = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
